---
functional:
  - Пользователь должен иметь возможность зарегистрироваться при помощи email, GitHub или Discord
  - Пользователь должен иметь возможность авторизоваться при помощи email, GitHub или Discord
  - Пользователь должен иметь возможность воспользоваться функцией восстановления пароля, если его забыл
  - Пользователь имеет возможность создать игру со своими параметрами
  - Пользователь должен иметь возможность отменить созданную им игру
  - Пользователь должен иметь возможность присоединиться к сторонней игре
  - Пользователь может писать в общий и личный чат
  - Пользователь должен иметь возможность приглашать других пользователей в игру, принимать и отклонять приглашения других
  - Пользователю выводится подробный список рейтинга игроков, турниров и история игр
  - Пользователь имеет возможность создать турнир
  - Пользователь может фильтровать рейтинг игроков и воспользоваться поиском по имени
  - Пользователь может отслеживать активность другого пользователя
  - Пользователь может просматривать подробности о задачах и создавать их
  - В игре пользователь должен видеть окно со своим кодом и кодом соперника
  - В игре пользоветелю видно условие, время и вывод задачи
  - В игре пользователь имеет возможность поменять язык программирования
  - В игре пользователь имеет возможность писать в чат
  - В игре пользователь имеет возможность сдаться, сбросить код и проверить решение кода
non-functional:
  - Сайт должен быть разработан с учётом удобства использования и оптимизирован для скорости работы
  - Сайт должен быть безопасным и защищать данные пользователя
  - Сайт должен быть удобным на мобильном устройстве
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров
  - Сайт должен быть способен обрабатывать большое количество трафика
implicit:
  - Сайт и его функции (поля, таблицы) отображаются корректно
  - У сайта есть выбор языка
  - Переходы между страницами работают корректно
  - При обновлении страницы пользователь остаётся на той странице, на которой перезагружался

